const DEFAULT={allowance:2500,budgets:{"Dates":700,"Electric + Water":700,"MariBank Savings":400,"Laundry":150,"Food & Daily Expenses":450,"Emergency / Extra":100},transactions:[]};
const cloneDefault=()=>JSON.parse(JSON.stringify(DEFAULT));
function normalize(raw={}){return {allowance:Number(raw.allowance)||DEFAULT.allowance,budgets:{...DEFAULT.budgets,...(raw.budgets||{})},transactions:Array.isArray(raw.transactions)?raw.transactions:[]}}
function load(){try{return normalize(JSON.parse(localStorage.getItem('pocketBudget')||'{}'))}catch{return cloneDefault()}}
let state=load();
const peso=n=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP',maximumFractionDigits:2}).format(n);
const saveState=document.querySelector('#saveState');
function save(){localStorage.setItem('pocketBudget',JSON.stringify(state));saveState.textContent='Saved locally';render()}
function totals(){const spent={};Object.keys(state.budgets).forEach(k=>spent[k]=0);state.transactions.forEach(t=>spent[t.category]=(spent[t.category]||0)+Number(t.amount));return spent}
function render(){const spent=totals(),totalSpent=Object.values(spent).reduce((a,b)=>a+b,0);document.querySelector('#allowance').textContent=peso(state.allowance);document.querySelector('#remaining').textContent=peso(state.allowance-totalSpent);const cards=document.querySelector('#cards');cards.innerHTML='';Object.entries(state.budgets).forEach(([name,budget])=>{const s=spent[name]||0,r=budget-s,pct=Math.min(100,(s/budget)*100||0);cards.insertAdjacentHTML('beforeend',`<article class="card"><div class="cardTop"><h3>${name}</h3><span>${peso(budget)}</span></div><div class="money ${r<0?'over':''}">${peso(r)} left</div><span>${peso(s)} spent</span><div class="bar"><i style="width:${pct}%"></i></div></article>`)});const sel=document.querySelector('#category');const current=sel.value;sel.innerHTML=Object.keys(state.budgets).map(x=>`<option>${x}</option>`).join('');if(current&&state.budgets[current]!=null)sel.value=current;const list=document.querySelector('#transactions');list.innerHTML=state.transactions.length?'':'<p>No transactions yet.</p>';[...state.transactions].reverse().slice(0,30).forEach(t=>list.insertAdjacentHTML('beforeend',`<div class="tx"><div><b>${t.description||t.category}</b><br><small>${t.category} • ${new Date(t.date).toLocaleString()}</small></div><b>${peso(t.amount)}</b><button aria-label="Delete transaction" data-id="${t.id}">×</button></div>`));}
document.querySelector('#txForm').addEventListener('submit',e=>{e.preventDefault();const amount=Number(document.querySelector('#amount').value);if(!amount)return;saveState.textContent='Saving…';state.transactions.push({id:crypto.randomUUID?.()||Date.now().toString(),category:document.querySelector('#category').value,amount,description:document.querySelector('#description').value.trim(),date:new Date().toISOString()});e.target.reset();save()});
document.querySelector('#transactions').addEventListener('click',e=>{if(e.target.dataset.id){state.transactions=state.transactions.filter(t=>t.id!==e.target.dataset.id);save()}});
const clear=()=>{if(confirm('Clear this week’s actual transactions?')){state.transactions=[];save()}};document.querySelector('#resetWeek').onclick=clear;document.querySelector('#clearTx').onclick=clear;
document.querySelector('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`pocket-budget-backup-${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
document.querySelector('#importFile').onchange=async e=>{try{const file=e.target.files?.[0];if(!file)return;const obj=JSON.parse(await file.text());if(!obj.budgets||!Array.isArray(obj.transactions))throw Error();state=normalize(obj);save();alert('Backup imported.')}catch{alert('That backup file is not valid.')}finally{e.target.value=''}};
const standalone=window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true;
const isiOS=/iphone|ipad|ipod/i.test(navigator.userAgent);
if(isiOS&&!standalone&&!localStorage.getItem('dismissInstallTip'))document.querySelector('#iosTip').hidden=false;
document.querySelector('#dismissTip').onclick=()=>{document.querySelector('#iosTip').hidden=true;localStorage.setItem('dismissInstallTip','1')};
const offlineStatus=document.querySelector('#offlineStatus');
async function checkOffline(){if(!('serviceWorker'in navigator)){offlineStatus.textContent='Offline caching is not supported in this browser.';return}try{await navigator.serviceWorker.ready;const cache=await caches.open('pocket-budget-v2');const keys=await cache.keys();offlineStatus.textContent=keys.length>=5?'Ready for offline use on this device.':'The app is installing its offline files. Keep this page open briefly and check again.'}catch{offlineStatus.textContent='Offline cache is not ready yet. Reload once while online.'}}
document.querySelector('#testOffline').onclick=checkOffline;
window.addEventListener('online',()=>{saveState.textContent='Saved locally'});window.addEventListener('offline',()=>{saveState.textContent='Offline • saved locally'});
if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js').then(()=>checkOffline()).catch(()=>{offlineStatus.textContent='Offline cache could not be installed. Make sure the site is opened over HTTPS.'})}
render();
